### ISSUE TITLE
Negative interaction with git-gutter-fringe

### ISSUE THREAD

**Issue by elken** [radian-software/apheleia#115]
Not sure where this should be reported, but when using `git-gutter-fringe` the fringe doesn't seem to update correctly.

Before save:
![image](https://user-images.githubusercontent.com/2872862/184597517-2f2c0e1b-a920-43bb-b0fd-5b8be720daa6.png)

After save which triggers `apheleia-format-buffer`:

![image](https://user-images.githubusercontent.com/2872862/184597584-5255c3f1-40a3-41c5-886b-8f6f19724ada.png)

I've tried adding advice to update the gutter after `apheleia--format-after-save` runs but that doesn't seem to resolve it until _another_ save happens or the timer triggers:
Advice:
![image](https://user-images.githubusercontent.com/2872862/184597791-0f40ba0a-79e7-4f57-97cf-5667741fe3c7.png)

Issue:
![image](https://user-images.githubusercontent.com/2872862/184597718-81bcc12c-ed15-4935-b716-6eca29ceda18.png)

**Comment by raxod502** [comment]
That's interesting. I've had some issues with git-gutter update hooks in the past. I just tested now and in my configuration, I _think_ it works as expected:

<details>

Before modification (no changes from HEAD)

![image](https://user-images.githubusercontent.com/6559064/188282012-3b0f53bf-e632-4577-8ce9-c3f7b28494c1.png)

Adding newline

![image](https://user-images.githubusercontent.com/6559064/188282030-5cf75266-7a35-4280-b70e-04985abaec29.png)

Saving, Apheleia reindents other lines using gofmt and git-gutter seems to update accordingly

![image](https://user-images.githubusercontent.com/6559064/188282050-defe8931-8b8b-4646-bc1b-cf6a16788920.png)

</details>

I believe this is because I have this configuration in [Radian](https://github.com/radian-software/radian):

https://github.com/raxod502/radian/blob/68e7fd41a20429456a1938430e6e13e6c0a3029b/emacs/radian.el#L4708-L4729

**Comment by elken** [comment]
Ah that looks like it might work, I'll try and see if that resolves it.

If it resolves it, might be a good candidate for a wiki post or something

**Comment by elken** [comment]
Yeah seems like this was some doom weirdness.

We use a similar hook to init and it just wasn't being invoked correctly!

**Comment by raxod502** [comment]
I turned on the wiki in case you wanted to use that. (You should also have access to configure this.) Might make more sense to put in the README though unless we have a lot of content.

**Comment by elken** [comment]
I have added a page for this.

> Might make more sense to put in the README though unless we have a lot of content.

My worry there is the README becomes just a load of hacks on working around various packages

**Comment by raxod502** [comment]
Heh, fair enough. Think it's worth mentioning in the README that there is wiki content? Most repos don't have it.
