### ISSUE TITLE
Allow emacs commands for formatting/allow using `eglot-format-buffer`?

### ISSUE THREAD

**Issue by chriselrod** [radian-software/apheleia#153]
I'd like to be able to use `eglot-format-buffer` as the command to format the buffer on save.
I'm currently using:
```elisp
# credit: https://go.googlesource.com/tools/+/refs/heads/master/gopls/doc/emacs.md
(defun elrod/eglot-format-buffer-on-save ()
  "Call `eglot-format-buffer` when saving."
  (add-hook 'before-save-hook #'eglot-format-buffer -10 t))
(add-hook 'eglot-managed-mode-hook #'elrod/eglot-format-buffer-on-save)
```
but would like to switch to aphelia.

The motivation for going through `eglot` rather than using the formatter directly is Julia.
Julia has a lot of JIT latency.
Running a script that loads and runs the formatter; `fmt.jl`:
```julia
#!/usr/bin/env -S julia -O1 
import JuliaFormatter
foreach(JuliaFormatter.format, ARGS)
```
takes seconds.
```julia
$ time fmt.jl ~/.julia/dev/LoopVectorization/src/broadcast.jl 
2.755 secs
```
However, with eglot, the LanguageServer's persistence means that future formats of the same project are reasonably fast.

I can emulate this via starting a Julia daemon
```julia
$ time juliaclient fmt.jl ~/.julia/dev/StrideArrays/
0.467 secs
```
but, then needing to start and manage the daemon is a bit of a hassle.
Or trying to compile the script into an executable, which is probably an even bigger hassle.

This same slowness is also much of aphelia's appeal: my approach for formatting on save locks up emacs for those seconds while the formatter runs!
Apherlia's approach of running it in the background is much nicer, but I'd still rather not have it take seconds on principle.

(Support for more formatters than supported by eglot is also appealing).

**Comment by raxod502** [comment]
Apheleia does support Elisp based formatters, can you integrate it that way?

**Comment by chriselrod** [comment]
Thanks for pointing that out, not sure how I missed it.
I tried
```elisp
(use-package apheleia
  :config
  (apheleia-global-mode +1))
(require 'cl-lib)
(cl-defun apheleia-indent-eglot-managed-buffer
    (&key buffer scratch callback &allow-other-keys)
  "Copy BUFFER to SCRATCH, then format scratch, then call CALLBACK."
  (with-current-buffer buffer
    (let ((tmp (generate-new-buffer "tmpbuffer")))
      ;; backup
      (copy-to-buffer tmp (point-min) (point-max))
      (eglot-format-buffer)
      ;; now we copy to scratch
      (copy-to-buffer scratch (point-min) (point-max))
      ;; and copy tmp back
      (with-current-buffer tmp
        (copy-to-buffer buffer (point-min) (point-max)))
      (kill-buffer tmp)
      (funcall callback))))

(add-to-list 'apheleia-formatters
                   '(eglot-managed . apheleia-indent-eglot-managed-buffer))

(add-to-list 'apheleia-mode-alist '(julia-mode . eglot-managed))
```
At least two problems with this:
1. After formatting, point moves to the start of the buffer. eglot's formatting is normally good about keeping it in place, and apheleia 
2. It is inefficient, probably copying buffer contents a lot more than necessary.

I originally tried something like
```elisp
(cl-defun apheleia-indent-eglot-managed-buffer
    (&key buffer scratch callback &allow-other-keys)
  "Copy BUFFER to SCRATCH, then format scratch, then call CALLBACK."
  (with-current-buffer buffer
    (copy-to-buffer scratch (point-min) (point-max))
    (eglot-format-buffer)
    )
  (with-current-buffer scratch
    (funcall (with-current-buffer buffer major-mode))
    (eglot-format-buffer)
    (funcall callback)))
```
which copies less often, but got a wrong-type-argument error from eglot when it looked for scratch's path. I probably messed something up here/need to set something else with scratch?

Formatting `buffer` itself works, but that means I need to first copy it to a scratch buffer, and then swap them, meaning 3 copies total instead of 1 (0 would of course be ideal).

I suspect the first problem is related, i.e. I shouldn't be formatting `buffer` and swapping, but need to setup `scratch` correctly?

**Comment by raxod502** [comment]
So, the scratch buffer provided by `apheleia--run-formatter-function` will already have the contents of the original buffer copied into it. Also, you should be able to format that buffer directly. The thing to fix here is the
> wrong-type-argument error from eglot when it looked for scratch's path
which I think you should be able to resolve by

```elisp
(let ((buffer-file-name (buffer-local-value 'buffer-file-name buffer)))
  (eglot-format-buffer))
(funcall callback)
```

This will work with zero additional copies.

I think the issues with point getting reset to the beginning are because you're modifying the original buffer, which messes up point.

Does that seem right?

**Comment by chriselrod** [comment]
With
```elisp
(use-package apheleia
  :config
  (apheleia-global-mode +1))
(require 'cl-lib)
(cl-defun apheleia-indent-eglot-managed-buffer
    (&key buffer scratch callback &allow-other-keys)
  "Copy BUFFER to SCRATCH, then format scratch, then call CALLBACK."
  (with-current-buffer scratch
    (let ((buffer-file-name (buffer-local-value 'buffer-file-name buffer)))
      (eglot-format-buffer))
    (funcall callback)))

(add-to-list 'apheleia-formatters
             '(eglot-managed . apheleia-indent-eglot-managed-buffer))
(add-to-list 'apheleia-mode-alist '(julia-mode . eglot-managed))
```
I get `jsonrpc-error: "No current JSON-RPC connection"`.
Calling `M-x eglot-format-buffer` works.
JSON-RPC of course is used with the LSP, so something there seems to be going wrong.

**Comment by raxod502** [comment]
I set up EGLOT on my end and fixed your advice:
```elisp
(cl-defun apheleia-indent-eglot-managed-buffer
        (&key buffer scratch callback &allow-other-keys)
      "Copy BUFFER to SCRATCH, then format scratch, then call CALLBACK."
      (with-current-buffer scratch
        (setq-local eglot--cached-server
                    (with-current-buffer buffer
                      (eglot-current-server)))
        (let ((buffer-file-name (buffer-local-value 'buffer-file-name buffer)))
          (eglot-format-buffer))
        (funcall callback)))
```

Here's how I found out the right solution. First I enabled `M-x toggle-debug-on-error` to see the stacktrace of `jsonrpc-error: "No current JSON-RPC connection"`. That showed me [`eglot--current-server-or-lose`](https://github.com/joaotavora/eglot/blob/e501275e06952889056268dabe08ccd0dbaf23e5/eglot.el#L1763-L1766). I tested evaluating `(eglot-current-server)` in the buffer to make sure it was returning non-nil, as expected. Then the issue is the function is returning nil in the scratch buffer. Looking at [`eglot-current-server`](https://github.com/joaotavora/eglot/blob/e501275e06952889056268dabe08ccd0dbaf23e5/eglot.el#L1750-L1761), the reason is pretty clear, it is looking at buffer-local variables and the major mode to look up the server connection. I added a step to copy the server context to the scratch buffer and it started working (very quickly too, great user experience!).

**Comment by chriselrod** [comment]
That works for me, many thanks!

Also, thank you for explaining how it was you debugged it.
`toggle-debug-on-error` is very useful -- I'll use that and take a look at the source next time I run into a problem.

**Comment by raxod502** [comment]
The advice on EGLOT from https://github.com/radian-software/apheleia/issues/153#issuecomment-1452783713?

**Comment by raxod502** [comment]
Oh. My comment said "I fixed your advice" so I assumed it was an advice, but looking back, I guess it wasn't an advice, so I'm not sure why my original comment was talking about an advice. Oops.

Yes, it makes sense to add a formatter function that uses EGLOT. Although it shouldn't be called `apheleia-indent-eglot-managed-buffer`, because it's not indentation code, it's arbitrary formatting. I would suggest perhaps `apheleia-format-eglot-buffer`. Let's start there.
