### ISSUE TITLE
Main branch is not protected from pushes

### ISSUE THREAD

**Issue by mohkale** [radian-software/apheleia#165]
Hi,

Apologies. I accidentally did a git push to the main branch from some features I was working on and it wasn't rejected. I then tried to force push back to where we were before my push but that was rejected :upside_down_face:. I ended up just adding 3 revert commits for what I was doing so we should be back to a stable position. At some point it would be nice if we could add a rule to only allow merges to the main branch from PRs.

**Comment by raxod502** [comment]
I think (now that we are in a GitHub organization) you should have the necessary admin permissions to change these settings on the repo, and I don't mind if you do. For now, I left direct pushes allowed, but also configured it so that force pushes are allowed. If you think it's better to disable both, I'm fine with that.

**Comment by mohkale** [comment]
Neat, didn't notice. I think for a multi-user org we should have rules in place preventing any one person from going rogue and doing something to the detriment of other users. I've gone ahead and disabled force pushing and enabled the option to only allow main branch pushes from pull requests.

**Comment by raxod502** [comment]
Sounds good to me.
