### ISSUE TITLE
Sorry for the beginner question!

### ISSUE THREAD

**Issue by ukiran03** [radian-software/apheleia#305]
I want to set an offset of 4 using `clang-format`. Here is the code:
```emacs-lisp
(use-package apheleia
  :init
  (setf (alist-get 'clang-format apheleia-formatters)
        '("clang-format" "--offset=4")))
```
It was not working as expected. Could you please help out?

**Comment by ZharMeny** [comment]
The `--offset` option works as intended with the example you provided, but it seems you misunderstood what the option does; it is used to start formatting from the offset of that much bytes since the beginning of the file.  If you want to use 4 spaces for indentation instead, you can use `"--style={IndentWidth: 4}"` option, or create a `.clang-format` file instead.
